### ISSUE TITLE
invalid_credentials: OAuth2::Error,

### ISSUE THREAD

**Issue by judearasu** [oauth-xx/oauth2#111]
I am developing a strategy using oauth2 for bitly.Credentials which i am using was correct one, but i am getting this error like this.

On sigin i am getting the error  like this

(bitly) Callback phase initiated.
(bitly) Authentication failure! invalid_credentials: OAuth2::Error, access_token=1da90d13c47ddae330e5526d50c459a039b02a4a&login=judearasu&apiKey=R_af262250800b9bc92ca06605ce056608

Can you please help on this

**Comment by galois17** [comment]
It's been a few years... This should work since I've done this a while back.

Just to help others....
``
client = OAuth2::Client.new(client_id, secret, :site => 'https://api-ssl.bitly.com',
          :token_url => '/oauth/access_token')
client.auth_code.authorize_url(:redirect_uri => YOUR_CALLBACK).gsub(/api-ssl\./,'')
client.auth_code.get_token(code, :redirect_uri => YOUR_CALLBACK, :parse => :query)
``

You may reopen this if this doesn't work and also show us the code.
