### ISSUE TITLE
Getting a token with a code while providing username and password

### ISSUE THREAD

**Issue by superlou** [oauth-xx/oauth2#140]
I am trying to access the Reddit OAuth 2.0 API, and have been able to request and authorization code succesfully based on the information at https://github.com/reddit/reddit/wiki/OAuth2.  However, when I try to exchange it for a token, I get a 401 error.  I believe I'm not properly providing the username and password.

I feel like some combination of `token = client.auth_code.get_token('code_value', :redirect_uri => 'http://localhost:8080/oauth/callback')` and `token = client.password.get_token('username', 'password')` would be the right way, but I'm not sure how to make the call.  I tried the following without any luck:

```
    access_token = @oauth.auth_code.get_token(params['code'],
                                          :redirect_uri => @oauth.redirect_uri,
                                          :headers => {
                                              'grant_type' => 'authorization_code',
                                              'username' => [my client id],
                                              'password' => [my client secret]
                                          })
```

**Comment by galois17** [comment]
Well, it's been a few years. Hopefully, you have found the solution. I've done this with Reddit before. To do the exchange for a token per their doc, you need to supply the basic auth header. You should use: 
``
token = client.auth_code.get_token('code_value', :redirect_uri => 'http://localhost:8080/oauth/callback', :headers => {'Authorization' => "Basic xxyyzz"})
``
where xxyyzz is the base64 encoded string of the client_id:secret since this is how basic auth is done.

This should take care of this request.
