### ISSUE TITLE
Handle Faraday::Error::ConnectionFailed

### ISSUE THREAD

**Issue by mbleigh** [oauth-xx/oauth2#152]

**Comment by hgani** [comment]
Hi guys,

If we wrap the original Faraday::Error::ConnectionFailed object inside our own exception (e.g. OAuth2::ConnectionFailed as suggested by @mbleigh), we won't lose any root information.

This way gem users can handle the error in an abstracted way (i.e. simply rescue OAuth2::ConnectionFailed), so that when Faraday's implementation changes or when we decide to move away from Faraday, *most* gem users won't be affected.

Thanks

**Comment by riffraff** [comment]
we run into this occasionally when using omniauth with google-oauth2 strategy, because omniauth-oauth2 catches `SocketError`, but `Faraday::ConnectionFailed` is not a subclass of that. 

We have a workaround which involves an extra middleware but it's clunky, if we had a `OAuth2::ConnectionFailed` then it could be handled properly in omniauth-oauth2 and we'd be happier. 

https://github.com/intridea/omniauth-oauth2/blob/v1.4.0/lib/omniauth/strategies/oauth2.rb#L77

**Comment by dblessing** [comment]
Came here to create an issue on this very thing - specific to what @riffraff said about Google OAuth2 and Omniauth. I originally suggested that `omniauth-oauth2` (this gem is a dependency of `omniauth-oauth2` and `omniauth-oauth2` is used by most OmniAuth OAuth2 implementations including `omniauth-google-oauth2`. 

I initially sent a PR to `omniauth-oauth2` at https://github.com/omniauth/omniauth-oauth2/pull/129, but they were hesitant to catch a specific error like Faraday. Instead they would prefer to catch an `OAuth2` namespaced error which would be agnostic of the underlying HTTP implementation in case this library decides to change from Faraday to something else later on. It makes sense.

**Comment by pboling** [comment]
That makes a lot of sense.  I don't have much time to dedicate to a PR for that, so if anyone else does, please do. @dblessing @riffraff
