### ISSUE TITLE
Should the refresh! method in AccessToken have the exclamation mark

### ISSUE THREAD

**Issue by tryceattack** [oauth-xx/oauth2#211]
It seems to not mutate the current accessToken. And to change the accessToken requires an assignment statement.

**Comment by tryceattack** [comment]
well, i did some reading on !, seems like ! does not always imply modifying the receiver. That's pretty confusing...

**Comment by xtagon** [comment]
Sometimes it indicates modifying the receiver, sometimes it is used to indicate that an exception is thrown instead of a success return value, and sometimes it is used to indicate that the method performs side effects. I've seen it used in all those ways in different code bases.

In any case, it's not worth making a breaking change.
