### ISSUE TITLE
[MACToken] Client#get_token's access_token_class parameter is broken

### ISSUE THREAD

**Issue by yonekawa** [oauth-xx/oauth2#248]
https://github.com/intridea/oauth2/blob/master/lib/oauth2/client.rb#L141

If we try to set `access_token_class` to `MACToken`, `MACToken#signature` fail with `TypeError: no implicit conversion of Hash into String`.

Because, `from_hash` passes (Client, String, Hash) parameters into constructor.
https://github.com/intridea/oauth2/blob/master/lib/oauth2/access_token.rb#L13

However, MACToken's constructor is (Client, String, String, Hash). 3rd parameter is `secret`.
https://github.com/intridea/oauth2/blob/master/lib/oauth2/mac_token.rb#L30

I think we don't need `access_token_class` parameter because we can use `MacToken.from_access_token`.
We should delete it parameter. How about it?

**Comment by xtagon** [comment]
@yonekawa Is this still an open issue? Asking because this was created over a year ago

**Comment by pboling** [comment]
It does appear to still be an issue as the code in question hasn't changed.

**Comment by yonekawa** [comment]
Yes, the code hasn't changed yet.
https://github.com/oauth-xx/oauth2/blob/master/lib/oauth2/access_token.rb#L14

**Comment by pboling** [comment]
There will not likely be action on this until we get a PR from someone motivated to improve the situation.  The team of maintainers has a lot on our plate preparing for the next release, and this issue is only a bug if the code is used in a particular way.  I haven't used it, but the spec passes.  If there is another use case where this doesn't work someone needs to write a spec.

https://github.com/oauth-xx/oauth2/blob/fb502c755ed8801aa5d4575f18b86a9b7ecf9f5e/spec/oauth2/mac_token_spec.rb

**Comment by pboling** [comment]
Added to 2.0.0 release milestone. I'll try to get this working...

**Comment by stanhu** [comment]
I think we should just drop MAC token support: https://github.com/oauth-xx/oauth2/pull/589

**Comment by pboling** [comment]
@yonekawa Are you aware of a live implementation anywhere that is using MAC Token Draft 05 (latest)?  The draft expired many years ago, and it is looking like we'll just drop support for it with v2, so if you know of any use cases please speak up!
