### ISSUE TITLE
Faraday 0.14.0 is released

### ISSUE THREAD

**Issue by johansmitsnl** [oauth-xx/oauth2#373]
Faraday 0.14.0 is released and it can't upgrade to this version because the current version is is pinned to < 0.13.
There is a commit that raises the level but this it not yet released (https://github.com/oauth-xx/oauth2/commit/cae5ae3e53e6e853f06933283fbebea1c0eac96e).

In my case it was updating the gemfile to:
```
...
Using omniauth-oauth2 1.0.2 (was 1.5.0)
Using omniauth-facebook 1.4.0 (was 4.0.0)
Using omniauth-google-oauth2 0.2.2 (was 0.5.3)
...
``` 

That does not seems like a good upgrade. Updated my dependencies to prevent downgrading but it might need some attention.

**Comment by pboling** [comment]
We are working on the next release, which will be `2.0.0`.

Here's the damage if you can spare any cycles to chip in.  We are resurrecting a dead project, that had mothballed for a while.

https://github.com/oauth-xx/oauth2/milestone/1

**Comment by stefansedich** [comment]
Can we get a point release to cover this? I am also hitting this and it would be great to be able to upgrade.

**Comment by pboling** [comment]
The short answer is no, but the new version, despite being "major", won't break anything for most people.  We'll cover everything in the changelog release notes.  The major bump is required as per SemVer 2.0, because there are some technically breaking changes.  We are not dropping any support for any versions of Ruby in this release though (and in fact are adding some to the official list), so no worries there.

**Comment by pboling** [comment]
Closing this in favor of #378
