### ISSUE TITLE
Release 1.4.1 with relaxed faraday dependency

### ISSUE THREAD

**Issue by dalibor** [oauth-xx/oauth2#404]
Hey Folks!

Any chance we could release 1.4.1 with relaxed faraday dependency as per this PR https://github.com/oauth-xx/oauth2/pull/397? Also, why lock the top version if we don't know that Faraday will change their API? What about locking it after the fact, i.e. if Faraday API changes?

I would have opened a patch, but there is no 1.4.0 stable branch.

Thanks!

**Comment by pboling** [comment]
We have already relaxed the version on master.  Please test master if you are able to switch.  We may release a pre-release version of the gem soon.  It will be a major version bump, and it will include breaking changes.

I was not involved in previous releases of oauth2, so this will be my first.  From my reading it seems that the reason for capping the faraday version is out of precaution, since faraday is known for changing their API and breaking lots of shit without warning, and without following semver.

**Comment by dalibor** [comment]
Ok, thanks for the details.
